version: '3.4'

networks:
  weatherapp:

services:
  appdb:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=pass123!
    networks:
      - weatherapp

  weatherapi:
    container_name: weather-app
    image: ${DOCKER_REGISTRY-}weatherapi
    build:
      context: .
      dockerfile: WeatherApi/Dockerfile
    ports:
      - 8001:80
    depends_on:
      - appdb
    environment:
      - DB_HOST=appdb
      - DB_NAME=WeatherApp
      - DB_SA_PASSWORD=pass123!
    networks:
      - weatherapp
